from .base import Instruction
from .instructions import (
    Add,
    AddAssign,
    Assign,
    AssignDeref,
    CallAssign,
    CallFunction,
    Clone,
    Decrement,
    Div,
    Free,
    FreeVec,
    HeapAlloc,
    IfElse,
    Increment,
    Mul,
    Nop,
    Print,
    Random,
    Ref,
    ReturnFunction,
    ReturnIfEquals,
    Set,
    StackVar,
    StackVarFromVar,
    StaticArray,
    Sub,
    VecNew,
    VecPush,
    VecPushDeref,
    calc_frame_size,
)

__all__ = [
    "CallAssign",
    "Clone",
    "AssignDeref",
    "Free",
    "FreeVec",
    "Set",
    "Nop",
    "ReturnFunction",
    "Decrement",
    "CallFunction",
    "HeapAlloc",
    "Ref",
    "StackVar",
    "StaticArray",
    "VecNew",
    "VecPush",
    "ReturnIfEquals",
    "AddAssign",
    "calc_frame_size",
    "VecPushDeref",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Increment",
    "Print",
    "IfElse",
    "StackVarFromVar",
    "Random",
    "Assign",
]


__all__ = ["Instruction"]
